name = "Gradebooks"
uuid = "27ffb4fc-0c2c-49fd-927d-7f1063d71ffd"
version = "0.1.0-dev"
authors = ["Joby M. Anthony III"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
OteraEngine = "b2d7f28f-acd6-4007-8b26-bc27716e5513"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
CSV = "0.10.15"
DataFrames = "1.8.1"
Dates = "1.11.0"
Distributed = "1.11.0"
Glob = "1.4.0"
JSON = "1.3.0"
OteraEngine = "1.1.3"
Preferences = "1.5.1"
PrettyTables = "3.1.2"
Printf = "1.11.0"
RecipesBase = "1.3.4"
Revise = "3.12.3"
Tables = "1.12.1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
